# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActuationAngle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ActuationAngle.proto',
  package='NetworkTable',
  syntax='proto3',
  serialized_pb=_b('\n\x14\x41\x63tuationAngle.proto\x12\x0cNetworkTable\";\n\x0e\x41\x63tuationAngle\x12\x14\n\x0crudder_angle\x18\x01 \x01(\x01\x12\x13\n\x0bwinch_angle\x18\x02 \x01(\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ACTUATIONANGLE = _descriptor.Descriptor(
  name='ActuationAngle',
  full_name='NetworkTable.ActuationAngle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rudder_angle', full_name='NetworkTable.ActuationAngle.rudder_angle', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='winch_angle', full_name='NetworkTable.ActuationAngle.winch_angle', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=97,
)

DESCRIPTOR.message_types_by_name['ActuationAngle'] = _ACTUATIONANGLE

ActuationAngle = _reflection.GeneratedProtocolMessageType('ActuationAngle', (_message.Message,), dict(
  DESCRIPTOR = _ACTUATIONANGLE,
  __module__ = 'ActuationAngle_pb2'
  # @@protoc_insertion_point(class_scope:NetworkTable.ActuationAngle)
  ))
_sym_db.RegisterMessage(ActuationAngle)


# @@protoc_insertion_point(module_scope)
