# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Satellite.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Sensors_pb2 as Sensors__pb2
from . import Uccms_pb2 as Uccms__pb2
from . import Value_pb2 as Value__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Satellite.proto',
  package='NetworkTable',
  syntax='proto3',
  serialized_pb=_b('\n\x0fSatellite.proto\x12\x0cNetworkTable\x1a\rSensors.proto\x1a\x0bUccms.proto\x1a\x0bValue.proto\"\xd2\x01\n\tSatellite\x12*\n\x04type\x18\x01 \x01(\x0e\x32\x1c.NetworkTable.Satellite.Type\x12&\n\x07sensors\x18\x02 \x01(\x0b\x32\x15.NetworkTable.Sensors\x12\"\n\x05uccms\x18\x03 \x01(\x0b\x32\x13.NetworkTable.Uccms\x12\"\n\x05value\x18\x04 \x01(\x0b\x32\x13.NetworkTable.Value\")\n\x04Type\x12\x0b\n\x07SENSORS\x10\x00\x12\t\n\x05UCCMS\x10\x01\x12\t\n\x05VALUE\x10\x02\x62\x06proto3')
  ,
  dependencies=[Sensors__pb2.DESCRIPTOR,Uccms__pb2.DESCRIPTOR,Value__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SATELLITE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='NetworkTable.Satellite.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SENSORS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UCCMS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=244,
  serialized_end=285,
)
_sym_db.RegisterEnumDescriptor(_SATELLITE_TYPE)


_SATELLITE = _descriptor.Descriptor(
  name='Satellite',
  full_name='NetworkTable.Satellite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='NetworkTable.Satellite.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sensors', full_name='NetworkTable.Satellite.sensors', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uccms', full_name='NetworkTable.Satellite.uccms', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='NetworkTable.Satellite.value', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SATELLITE_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=285,
)

_SATELLITE.fields_by_name['type'].enum_type = _SATELLITE_TYPE
_SATELLITE.fields_by_name['sensors'].message_type = Sensors__pb2._SENSORS
_SATELLITE.fields_by_name['uccms'].message_type = Uccms__pb2._UCCMS
_SATELLITE.fields_by_name['value'].message_type = Value__pb2._VALUE
_SATELLITE_TYPE.containing_type = _SATELLITE
DESCRIPTOR.message_types_by_name['Satellite'] = _SATELLITE

Satellite = _reflection.GeneratedProtocolMessageType('Satellite', (_message.Message,), dict(
  DESCRIPTOR = _SATELLITE,
  __module__ = 'Satellite_pb2'
  # @@protoc_insertion_point(class_scope:NetworkTable.Satellite)
  ))
_sym_db.RegisterMessage(Satellite)


# @@protoc_insertion_point(module_scope)
