# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SubscribeRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SubscribeRequest.proto',
  package='NetworkTable',
  syntax='proto3',
  serialized_pb=_b('\n\x16SubscribeRequest.proto\x12\x0cNetworkTable\"\x1f\n\x10SubscribeRequest\x12\x0b\n\x03uri\x18\x01 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SUBSCRIBEREQUEST = _descriptor.Descriptor(
  name='SubscribeRequest',
  full_name='NetworkTable.SubscribeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='NetworkTable.SubscribeRequest.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=71,
)

DESCRIPTOR.message_types_by_name['SubscribeRequest'] = _SUBSCRIBEREQUEST

SubscribeRequest = _reflection.GeneratedProtocolMessageType('SubscribeRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBEREQUEST,
  __module__ = 'SubscribeRequest_pb2'
  # @@protoc_insertion_point(class_scope:NetworkTable.SubscribeRequest)
  ))
_sym_db.RegisterMessage(SubscribeRequest)


# @@protoc_insertion_point(module_scope)
