# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Uccms.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Uccms.proto',
  package='NetworkTable',
  syntax='proto3',
  serialized_pb=_b('\n\x0bUccms.proto\x12\x0cNetworkTable\"\xfd\x06\n\x05Uccms\x12\x33\n\x11\x62oom_angle_sensor\x18\x01 \x01(\x0b\x32\x18.NetworkTable.Uccms.Uccm\x12\x38\n\x16rudder_motor_control_0\x18\x02 \x01(\x0b\x32\x18.NetworkTable.Uccms.Uccm\x12\x38\n\x16rudder_motor_control_1\x18\x03 \x01(\x0b\x32\x18.NetworkTable.Uccms.Uccm\x12\x37\n\x15winch_motor_control_0\x18\x04 \x01(\x0b\x32\x18.NetworkTable.Uccms.Uccm\x12\x37\n\x15winch_motor_control_1\x18\x05 \x01(\x0b\x32\x18.NetworkTable.Uccms.Uccm\x12/\n\rwind_sensor_0\x18\x06 \x01(\x0b\x32\x18.NetworkTable.Uccms.Uccm\x12/\n\rwind_sensor_1\x18\x07 \x01(\x0b\x32\x18.NetworkTable.Uccms.Uccm\x12/\n\rwind_sensor_2\x18\x08 \x01(\x0b\x32\x18.NetworkTable.Uccms.Uccm\x12\'\n\x05gps_0\x18\t \x01(\x0b\x32\x18.NetworkTable.Uccms.Uccm\x12\'\n\x05gps_1\x18\n \x01(\x0b\x32\x18.NetworkTable.Uccms.Uccm\x12\'\n\x05\x62ms_0\x18\x0b \x01(\x0b\x32\x18.NetworkTable.Uccms.Uccm\x12\'\n\x05\x62ms_1\x18\x0c \x01(\x0b\x32\x18.NetworkTable.Uccms.Uccm\x12\'\n\x05\x62ms_2\x18\r \x01(\x0b\x32\x18.NetworkTable.Uccms.Uccm\x12\'\n\x05\x62ms_3\x18\x0e \x01(\x0b\x32\x18.NetworkTable.Uccms.Uccm\x12\'\n\x05\x62ms_4\x18\x0f \x01(\x0b\x32\x18.NetworkTable.Uccms.Uccm\x12\'\n\x05\x62ms_5\x18\x10 \x01(\x0b\x32\x18.NetworkTable.Uccms.Uccm\x12/\n\raccelerometer\x18\x11 \x01(\x0b\x32\x18.NetworkTable.Uccms.Uccm\x1aM\n\x04Uccm\x12\x0f\n\x07\x63urrent\x18\x01 \x01(\x05\x12\x0f\n\x07voltage\x18\x02 \x01(\x05\x12\x13\n\x0btemperature\x18\x03 \x01(\x05\x12\x0e\n\x06status\x18\x04 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_UCCMS_UCCM = _descriptor.Descriptor(
  name='Uccm',
  full_name='NetworkTable.Uccms.Uccm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current', full_name='NetworkTable.Uccms.Uccm.current', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage', full_name='NetworkTable.Uccms.Uccm.voltage', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='NetworkTable.Uccms.Uccm.temperature', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='NetworkTable.Uccms.Uccm.status', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=846,
  serialized_end=923,
)

_UCCMS = _descriptor.Descriptor(
  name='Uccms',
  full_name='NetworkTable.Uccms',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='boom_angle_sensor', full_name='NetworkTable.Uccms.boom_angle_sensor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rudder_motor_control_0', full_name='NetworkTable.Uccms.rudder_motor_control_0', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rudder_motor_control_1', full_name='NetworkTable.Uccms.rudder_motor_control_1', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='winch_motor_control_0', full_name='NetworkTable.Uccms.winch_motor_control_0', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='winch_motor_control_1', full_name='NetworkTable.Uccms.winch_motor_control_1', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wind_sensor_0', full_name='NetworkTable.Uccms.wind_sensor_0', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wind_sensor_1', full_name='NetworkTable.Uccms.wind_sensor_1', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wind_sensor_2', full_name='NetworkTable.Uccms.wind_sensor_2', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gps_0', full_name='NetworkTable.Uccms.gps_0', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gps_1', full_name='NetworkTable.Uccms.gps_1', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bms_0', full_name='NetworkTable.Uccms.bms_0', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bms_1', full_name='NetworkTable.Uccms.bms_1', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bms_2', full_name='NetworkTable.Uccms.bms_2', index=12,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bms_3', full_name='NetworkTable.Uccms.bms_3', index=13,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bms_4', full_name='NetworkTable.Uccms.bms_4', index=14,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bms_5', full_name='NetworkTable.Uccms.bms_5', index=15,
      number=16, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accelerometer', full_name='NetworkTable.Uccms.accelerometer', index=16,
      number=17, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_UCCMS_UCCM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=923,
)

_UCCMS_UCCM.containing_type = _UCCMS
_UCCMS.fields_by_name['boom_angle_sensor'].message_type = _UCCMS_UCCM
_UCCMS.fields_by_name['rudder_motor_control_0'].message_type = _UCCMS_UCCM
_UCCMS.fields_by_name['rudder_motor_control_1'].message_type = _UCCMS_UCCM
_UCCMS.fields_by_name['winch_motor_control_0'].message_type = _UCCMS_UCCM
_UCCMS.fields_by_name['winch_motor_control_1'].message_type = _UCCMS_UCCM
_UCCMS.fields_by_name['wind_sensor_0'].message_type = _UCCMS_UCCM
_UCCMS.fields_by_name['wind_sensor_1'].message_type = _UCCMS_UCCM
_UCCMS.fields_by_name['wind_sensor_2'].message_type = _UCCMS_UCCM
_UCCMS.fields_by_name['gps_0'].message_type = _UCCMS_UCCM
_UCCMS.fields_by_name['gps_1'].message_type = _UCCMS_UCCM
_UCCMS.fields_by_name['bms_0'].message_type = _UCCMS_UCCM
_UCCMS.fields_by_name['bms_1'].message_type = _UCCMS_UCCM
_UCCMS.fields_by_name['bms_2'].message_type = _UCCMS_UCCM
_UCCMS.fields_by_name['bms_3'].message_type = _UCCMS_UCCM
_UCCMS.fields_by_name['bms_4'].message_type = _UCCMS_UCCM
_UCCMS.fields_by_name['bms_5'].message_type = _UCCMS_UCCM
_UCCMS.fields_by_name['accelerometer'].message_type = _UCCMS_UCCM
DESCRIPTOR.message_types_by_name['Uccms'] = _UCCMS

Uccms = _reflection.GeneratedProtocolMessageType('Uccms', (_message.Message,), dict(

  Uccm = _reflection.GeneratedProtocolMessageType('Uccm', (_message.Message,), dict(
    DESCRIPTOR = _UCCMS_UCCM,
    __module__ = 'Uccms_pb2'
    # @@protoc_insertion_point(class_scope:NetworkTable.Uccms.Uccm)
    ))
  ,
  DESCRIPTOR = _UCCMS,
  __module__ = 'Uccms_pb2'
  # @@protoc_insertion_point(class_scope:NetworkTable.Uccms)
  ))
_sym_db.RegisterMessage(Uccms)
_sym_db.RegisterMessage(Uccms.Uccm)


# @@protoc_insertion_point(module_scope)
