# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Value.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Value.proto',
  package='NetworkTable',
  syntax='proto3',
  serialized_pb=_b('\n\x0bValue.proto\x12\x0cNetworkTable\"\xac\x06\n\x05Value\x12&\n\x04type\x18\x01 \x01(\x0e\x32\x18.NetworkTable.Value.Type\x12\x12\n\nfloat_data\x18\x02 \x01(\x01\x12\x11\n\tbool_data\x18\x03 \x01(\x08\x12\x10\n\x08int_data\x18\x04 \x01(\x05\x12\x13\n\x0bstring_data\x18\x05 \x01(\t\x12\x12\n\nbytes_data\x18\x06 \x01(\x0c\x12\'\n\x05\x62oats\x18\x07 \x03(\x0b\x32\x18.NetworkTable.Value.Boat\x12/\n\twaypoints\x18\x08 \x03(\x0b\x32\x1c.NetworkTable.Value.Waypoint\x1a\xb6\x03\n\x04\x42oat\x12\x0e\n\x06m_mmsi\x18\x01 \x01(\x05\x12\x1a\n\x12m_navigationStatus\x18\x02 \x01(\x05\x12\x14\n\x0cm_rateOfTurn\x18\x03 \x01(\x02\x12\x16\n\x0em_highAccuracy\x18\x04 \x01(\x08\x12\x12\n\nm_latitude\x18\x05 \x01(\x01\x12\x13\n\x0bm_longitude\x18\x06 \x01(\x01\x12\r\n\x05m_sog\x18\x07 \x01(\x02\x12\r\n\x05m_cog\x18\x08 \x01(\x02\x12\x15\n\rm_trueHeading\x18\t \x01(\x05\x12\x13\n\x0bm_timeStamp\x18\n \x01(\x05\x12\x1b\n\x13m_maneuverIndicator\x18\x0b \x01(\x05\x12\x16\n\x0em_timeReceived\x18\x0c \x01(\x03\x12\x19\n\x11m_rateOfTurnValid\x18\r \x01(\x08\x12\x12\n\nm_sogValid\x18\x0e \x01(\x08\x12\x12\n\nm_cogValid\x18\x0f \x01(\x08\x12\x1a\n\x12m_trueHeadingValid\x18\x10 \x01(\x08\x12\x17\n\x0fm_positionValid\x18\x11 \x01(\x08\x12\x18\n\x10m_timeStampValid\x18\x12 \x01(\x08\x12\x1a\n\x12m_transcieverClass\x18\x13 \x01(\x05\x1a/\n\x08Waypoint\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"U\n\x04Type\x12\t\n\x05\x46LOAT\x10\x00\x12\x08\n\x04\x42OOL\x10\x01\x12\x07\n\x03INT\x10\x02\x12\n\n\x06STRING\x10\x03\x12\t\n\x05\x42YTES\x10\x04\x12\t\n\x05\x42OATS\x10\x05\x12\r\n\tWAYPOINTS\x10\x06\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_VALUE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='NetworkTable.Value.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLOAT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOOL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STRING', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BYTES', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOATS', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WAYPOINTS', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=757,
  serialized_end=842,
)
_sym_db.RegisterEnumDescriptor(_VALUE_TYPE)


_VALUE_BOAT = _descriptor.Descriptor(
  name='Boat',
  full_name='NetworkTable.Value.Boat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m_mmsi', full_name='NetworkTable.Value.Boat.m_mmsi', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_navigationStatus', full_name='NetworkTable.Value.Boat.m_navigationStatus', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_rateOfTurn', full_name='NetworkTable.Value.Boat.m_rateOfTurn', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_highAccuracy', full_name='NetworkTable.Value.Boat.m_highAccuracy', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_latitude', full_name='NetworkTable.Value.Boat.m_latitude', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_longitude', full_name='NetworkTable.Value.Boat.m_longitude', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_sog', full_name='NetworkTable.Value.Boat.m_sog', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_cog', full_name='NetworkTable.Value.Boat.m_cog', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_trueHeading', full_name='NetworkTable.Value.Boat.m_trueHeading', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_timeStamp', full_name='NetworkTable.Value.Boat.m_timeStamp', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_maneuverIndicator', full_name='NetworkTable.Value.Boat.m_maneuverIndicator', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_timeReceived', full_name='NetworkTable.Value.Boat.m_timeReceived', index=11,
      number=12, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_rateOfTurnValid', full_name='NetworkTable.Value.Boat.m_rateOfTurnValid', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_sogValid', full_name='NetworkTable.Value.Boat.m_sogValid', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_cogValid', full_name='NetworkTable.Value.Boat.m_cogValid', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_trueHeadingValid', full_name='NetworkTable.Value.Boat.m_trueHeadingValid', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_positionValid', full_name='NetworkTable.Value.Boat.m_positionValid', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_timeStampValid', full_name='NetworkTable.Value.Boat.m_timeStampValid', index=17,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='m_transcieverClass', full_name='NetworkTable.Value.Boat.m_transcieverClass', index=18,
      number=19, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=706,
)

_VALUE_WAYPOINT = _descriptor.Descriptor(
  name='Waypoint',
  full_name='NetworkTable.Value.Waypoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='NetworkTable.Value.Waypoint.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='NetworkTable.Value.Waypoint.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=708,
  serialized_end=755,
)

_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='NetworkTable.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='NetworkTable.Value.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='float_data', full_name='NetworkTable.Value.float_data', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bool_data', full_name='NetworkTable.Value.bool_data', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int_data', full_name='NetworkTable.Value.int_data', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='string_data', full_name='NetworkTable.Value.string_data', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bytes_data', full_name='NetworkTable.Value.bytes_data', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='boats', full_name='NetworkTable.Value.boats', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='waypoints', full_name='NetworkTable.Value.waypoints', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_VALUE_BOAT, _VALUE_WAYPOINT, ],
  enum_types=[
    _VALUE_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=842,
)

_VALUE_BOAT.containing_type = _VALUE
_VALUE_WAYPOINT.containing_type = _VALUE
_VALUE.fields_by_name['type'].enum_type = _VALUE_TYPE
_VALUE.fields_by_name['boats'].message_type = _VALUE_BOAT
_VALUE.fields_by_name['waypoints'].message_type = _VALUE_WAYPOINT
_VALUE_TYPE.containing_type = _VALUE
DESCRIPTOR.message_types_by_name['Value'] = _VALUE

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), dict(

  Boat = _reflection.GeneratedProtocolMessageType('Boat', (_message.Message,), dict(
    DESCRIPTOR = _VALUE_BOAT,
    __module__ = 'Value_pb2'
    # @@protoc_insertion_point(class_scope:NetworkTable.Value.Boat)
    ))
  ,

  Waypoint = _reflection.GeneratedProtocolMessageType('Waypoint', (_message.Message,), dict(
    DESCRIPTOR = _VALUE_WAYPOINT,
    __module__ = 'Value_pb2'
    # @@protoc_insertion_point(class_scope:NetworkTable.Value.Waypoint)
    ))
  ,
  DESCRIPTOR = _VALUE,
  __module__ = 'Value_pb2'
  # @@protoc_insertion_point(class_scope:NetworkTable.Value)
  ))
_sym_db.RegisterMessage(Value)
_sym_db.RegisterMessage(Value.Boat)
_sym_db.RegisterMessage(Value.Waypoint)


# @@protoc_insertion_point(module_scope)
