# Generated by Django 3.1.5 on 2021-03-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wind',
            name='Status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wind',
            name='WindDirection',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wind',
            name='WindReference',
            field=models.IntegerField(),
        ),
    ]
